from .my_exceptions import InvalidUrlError